parameters:
    zorbus_menu.menu.admin.class: Zorbus\MenuBundle\Admin\MenuAdmin
    zorbus_menu.item.admin.class: Zorbus\MenuBundle\Admin\ItemAdmin

    zorbus_menu.menu.entity.class: Zorbus\MenuBundle\Entity\Menu
    zorbus_menu.item.entity.class: Zorbus\MenuBundle\Entity\Item

    zorbus_menu.menu.controller.class: SonataAdminBundle:CRUD
    zorbus_menu.item.controller.class: SonataAdminBundle:CRUD

services:
    zorbus_menu.menu.admin:
        class: %zorbus_menu.menu.admin.class%
        arguments: [~, %zorbus_menu.menu.entity.class%, %zorbus_menu.menu.controller.class%]
        calls:
            - [setTranslationDomain, [MenuBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Menus, label: Menus }
    zorbus_menu.item.admin:
        class: %zorbus_menu.item.admin.class%
        arguments: [~, Zorbus\MenuBundle\Entity\Item, %zorbus_menu.item.controller.class%]
        calls:
            - [setTranslationDomain, [MenuBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Menus, label: Items }